module.exports = {
    BASE_URL: 'http://10.132.84.23:3001',
    KEY_STORAGE: 'projeto_extensao',
    TOKEN_FETCHED: 'TOKEN_FETCHED',
    PROJECT_FETCHED: 'PROJECT_FETCHED',
    USER_UPDATED: 'USER_UPDATED',
    USER_FETCHED: 'USER_FETCHED',
    USER_DELETED: 'USER_DELETED'
}
